name: vanilla_traceability
description: Vanilla Traceability App Development
version: 1.0.0+1

environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.2.0
  flutter_svg: ^2.0.1
  pin_code_fields: ^8.0.1
  dotted_border: ^2.1.0
  intl: ^0.18.0
  order_tracker: ^0.0.2

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/

  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterBold.ttf
          weight: 700
    - family: Urbanist
      fonts: 
        - asset: assets/fonts/UrbanistRomanSemiBold.ttf
          weight: 600
